### ISSUE TITLE
Possible Circular Dependency [Issuer and Certificate Don't Deploy]

### ISSUE THREAD

**Issue by mlladb** [eminaktas/kubedns-shepherd#25]
I've been trying to deploy this chart with Argo CD omitting the cert-manager deployment as I already have a deployment running.

ArgoCD can't deploy the `DNSClass` as  the mutating webhook `mdnsclass.kb.io` fails. 
The mutating webhook `mdnsclass.kb.io` won't work because the pods that handle it's requests won't boot. 
The pods won't boot because they are looking for a `Certificate`, via a secret, that hasn't been created yet and can't be due to the following annotations.

I assume the same issue problem occurs with a Helm deployment.

serving-cert.yaml
```
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
```

selfsigned-issuer.yaml
```
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
```

**Comment by eminaktas** [comment]
Hi @mlladb , thank you for bringing this issue to my attention! I think we should avoid adding the Helm Hooks If cert-manager installation is not enabled for certificates.

**Comment by eminaktas** [comment]
I was able to reproduce your case and the new PR fixes the issue on my test setup.

<img width="899" alt="Screenshot 2024-10-11 at 08 59 42" src="https://github.com/user-attachments/assets/e81ce1e2-1d56-4c01-951f-85c436eeffbf">

**Comment by eminaktas** [comment]
The fix has been merged. If the issue persists, please feel free to reopen this ticket.

**Comment by mlladb** [comment]
Hi @eminaktas. Thanks for the quick turnaround. The fix works in that I now have `Issuer` and `Certificate` resources being deployed. However I now have another circular dependency as ArgoCD can't deploy the `DNSClass`. 😄 

I believe this is because the application pods need to be running in order for the mutating webhook and validating web hook to run. Both of which intercept requests to create or update `dnsclasses`. Perhaps these can be deployed last after all other resources are deployed?
